name: Test data pipeline

on:
    push:
      branches:
        - main

jobs:
    test-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                path: main
            
          - name: Set up Miniconda 
            uses: conda-incubator/setup-miniconda@v2
            with: 
                python-version: 3.9 
                auto-update-conda: true 
                activate-environment: made_env 
                environment-file: main/environment.yml # The path to your environment.yml file use-mamba: true # Optional: for faster environment resolution using mamba
          - name: Initialize and activate Conda environment
            run: |
             conda init bash
             source ~/.bashrc
             conda activate made_env 
             conda info
             conda list
          
          - name: Run Python script
            run: | 
                chmod +x main/project/test.sh    
                main/project/test.sh