name: Test data pipeline

on:
    push:
      branches:
        - main

jobs:
    test-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                path: main
          - name: Config python
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'
          - name: Run Python script
            run: sh ./project/test.sh