name: Test data pipeline

on:
    push:
      branches:
        - main
      paths:
        - project/**.py
jobs:
    test-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                path: main
            
          - name: Install Python dependencies
            uses: py-actions/py-dependency-install@v4
            with:
                path: "main/requirements.txt"          
          - name: Run Python script
            run: | 
               sh main/project/test.sh
