name: Test data pipeline

on:
    push:
      branches:
        - main

jobs:
    test-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                path: main
          - name: Set up Miniconda 
            uses: conda-incubator/setup-miniconda@v2
            with: 
                python-version: 3.10 
                auto-update-conda: true 
                activate-environment: made_env 
                environment-file: main/environment.yml # The path to your environment.yml file use-mamba: true # Optional: for faster environment resolution using mamba
          - name: Run Python script
            run: sh main/project/test.sh